---
- name: net.ifnames
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX'
    line: GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"

- name: grub2-mkconfig
  shell:
    cmd: grub2-mkconfig
