---
- name: install httpd
  yum:
    name: httpd
    state: present

- name: run services
  service:
    name: httpd
    state: started

- name: check status
  ansible.builtin.service_facts:

- name: check status services
  ansible.builtin.debug:
    var: ansible_facts.services['httpd.service']

- name: create html directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/www/html

- name: create index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: open 80 port
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify:
    - restart firewalld
